document.write("<div class='header-wrapper'>");
document.write("    <!-- Help Menu -->");
document.write("    <div class='green-bg hide'>");
document.write("      <div class='wrap1200 clearfix'>");
document.write("        <ul class='do clearfix'>");
document.write("          <li><a class='email' href='mailto:info@rfhospital.org'><p class='for'>Email ID</p><p class='mail-address'>info@rfhospital.org</p></a></li>         ");
document.write("          <li><a class='toll no-link' href='javascript:;'><p class='for'>Toll Free Number</p><p>1-800-221-166</p></a></li>            ");
//document.write("          <li><a class='toll no-link' href='javascript:;'><p class='for'>24 hrs</p><p>1-800-221-166</p></a></li>         ");
document.write("          <li><a class='toll no-link' href='javascript:;'><p class='for'>Emergency</p><p>+91-22-6130-5005</p></a></li>         ");
document.write("          <li><a class='amb no-link' href='javascript:;'><p class='for'>Ambulance </p><p>1298</p></a></li>         ");
document.write("          <li class='border-mobile hide'><a class='nos' href='#'><p class='for'>Appointments</p><p>SMS 'RFH' to 55555</p></a></li>       ");
document.write("          <li class='whalf no-bl'><a class='request-a-doc' href='frmBookAnAppointment.aspx'>Request an Appointment</a></li>         ");
document.write("          <li class='whalf'><a class='find-a-doc' href='#' onClick='toggleSidebar()'>Find a doctor</a></li>");
document.write("          <li class='whalf'><a class='feedback' href='frmfeedback.aspx'>Feedback</a></li>");
document.write("        </ul>");
document.write("      </div>");
document.write("    </div>");
document.write("    <!-- End Help Menu -->");
document.write("    <!-- Header -->");
document.write("    <header class='relative clearfix'>");
document.write("      <!-- Header logo -->");
document.write("      <a id='hnh-logo' class='fl' href='http://www.rfhospital.org/'>Sir H. N. Reliance Foundation Hospital</a>");
document.write("      <!-- End Header logo --> ");
document.write("      <!-- Header Menu -->");
document.write("      <div id='mobile-header' class='clearfix'>");
document.write("        <a class='fr' id='simple-menu' href='#sidr-main'>Menu</a>");
document.write("      </div>");
document.write("      <div id='navigation' class='fr'> ");
document.write("        <ul id='menu' class='fr unstyled-list clearfix'>");
document.write("          <li>");
document.write("          	<a href='http://www.rfhospital.org/'>Home</a>");
document.write("          </li>");
document.write("          <li>");
document.write("            <a href='aboutus.html'>About Us</a>");
document.write("            <ul class='sub-menu about-position clearfix hide'>");
document.write("              <li class='clearfix'>            	");
/*document.write("                <ul class='sub-menu-list clearfix'>");
document.write("                  <li>");
document.write("                    <h3><a href='our-legacy.html'>Our Legacy: Sir Hurkissandas Nurrotamdas Hospital &amp; Research Centre</a></h3>");
document.write("                  </li>");
document.write("                  <li>");
document.write("                    <h3><a href='chairperson-message.html'>Chairperson's Message</a></h3>");
document.write("                  </li>");
document.write("                  <li>");
document.write("                    <h3><a href='values-behaviours.html'>Values & Behaviours</a></h3>");
document.write("                  </li>");
document.write("                </ul>");
document.write("                <ul class='sub-menu-list'>");
document.write("                  <li>");
document.write("                    <h3><a href='partners-in-care.html'>Management Team</a></h3>");
document.write("                  </li>");
document.write("                  <li>");
document.write("                    <h3><a href='about-us.html'>About Sir HN Reliance Foundation Hospital</a></h3>");
document.write("                  </li>");
document.write("                </ul>             ");*/
document.write("                <ul class='sub-menu-list clearfix'>");
document.write("                  <li>");
document.write("                    <h3><a href='respect-life.html'>Respect For Life</a></h3>");
document.write("                  </li>");
document.write("                  <li>");
document.write("                    <h3><a href='chairperson-message.html'>Chairperson's Message</a></h3>");
document.write("                  </li>");
document.write("                  <li>");
document.write("                    <h3><a href='our-pledge.html'>Our Pledge</a></h3>");
document.write("                  </li>");
document.write("                </ul>");
document.write("                <ul class='sub-menu-list'>");
document.write("                  <li>");
document.write("                    <h3><a href='our-values.html'>Our Values</a></h3>");
document.write("                  </li>");
document.write("                  <li>");
document.write("                    <h3><a href='the-hospital.html'>The Hospital</a></h3>");
document.write("                  </li>");
document.write("                  <li>");
document.write("                    <h3><a href='partners-in-care.html'>Management Team</a></h3>");
document.write("                  </li>");
document.write("                </ul>             ");
document.write("                <ul class='sub-menu-list last'>");
document.write("                  <li>");
document.write("                    <img src='img/submenu_img2.jpg' alt='Submenu Image'>");
document.write("                    <h3 class='hide'>Lorem Ipsum Proin gravida </h3>");
document.write("                    <p class='hide'>Nisbh vel velit auctor aliquet. Aenean sollicitudin.</p> ");
document.write("                  </li>");
document.write("                </ul>                 ");
document.write("              </li>");
document.write("            </ul>");
document.write("          </li>");
document.write("          <li>");
document.write("            <a href='care-centres.html'>Care Centres</a>");
document.write("            <ul class='sub-menu care-position clearfix hide'>");
document.write("              <!--<h3><a href='executive-health-checkup.html'>Executive Health Check Up</a></h3> -->");
document.write("              <li class='clearfix'>            	");
document.write("                <ul class='sub-menu-list'>");
document.write("                  <li>");
document.write("                    <ul class='sub-inner-page'>");
document.write("                    	");
document.write("                      <li>");
document.write("                        <a href='javascript:;' class='no-link'>Cardiac Sciences</a>");
document.write("                        <ul class='sub-inner-links'>");
document.write("                          <li><a href='cardiology.html'>Cardiology</a></li>");
document.write("                          <li><a href='cardiac-surgery.html'>Cardiac Surgery</a></li>");
document.write("                        </ul>");
document.write("                      </li>");
document.write("                      ");
document.write("                      <li>");
document.write("                        <a href='javascript:;' class='no-link'>Oncology Services</a>");
document.write("                        <ul class='sub-inner-links'>");
document.write("                          <li><a href='medical-oncology.html'>Medical Oncology</a></li>");
document.write("                          <li><a href='surgical-oncology.html'>Surgical Oncology</a></li>");
document.write("                          <li><a href='radiation-oncology.html'>Radiation Oncology</a></li>");
document.write("                        </ul>");
document.write("                      </li>");
document.write("                      ");
document.write("                      <li>");
document.write("                        <a href='javascript:;' class='no-link'>Neuro Sciences</a>");
document.write("                        <ul class='sub-inner-links'>");
document.write("                          <li><a href='neurology.html'>Neurology</a></li>");
document.write("                          <li><a href='neurosurgery.html'>Neuro Surgery</a></li>");
document.write("                          <li><a href='neuro-spine-surgery.html'>Neuro Spine Surgery</a></li>");
document.write("                          <li class='hide'><a href='javascript:;'>Psychiatry</a></li>");
document.write("                        </ul>");
document.write("                      </li>");
document.write("                      ");
document.write("                      <li>");
document.write("                        <a href='javascript:;' class='no-link'>Orthopaedics</a>");
document.write("                        <ul class='sub-inner-links'>");
document.write("                          <li><a href='orthopaedics.html'>Orthopaedics</a></li>");
document.write("                          <li><a href='spine-surgery.html'>Orthopaedic Spine Surgery</a></li>");
document.write("                        </ul> ");
document.write("                      </li> ");
document.write("                    	");
document.write("                      ");
document.write("                       ");
document.write("                      ");
document.write("                    </ul>");
document.write("                  </li>");
document.write("                </ul>              ");
document.write("                <ul class='sub-menu-list'>");
document.write("                  <li>");
document.write("                    <ul class='sub-inner-page'> ");
document.write("                    	");
document.write("                       <li>");
document.write("                        <a href='javascript:;'  class='no-link'>Uro-Genital Sciences</a>");
document.write("                        <ul class='sub-inner-links'>");
document.write("                          <li><a href='uro-genital-surgery.html'>Urology</a></li>");
document.write("                          <li><a href='nephrology.html'>Nephrology</a></li>");
document.write("                        </ul>");
document.write("                      </li> ");
document.write("                        ");
document.write("                      ");
document.write("                      <li>");
document.write("                        <a href='gynaecology-obstetrics.html'>Obstetrics &amp; Gynaecology</a>");
document.write("                      </li>");
document.write("                      ");
document.write("                      <li>");
document.write("                        <a href='javascript:;' class='no-link'>Paediatrics</a>");
document.write("                        <ul class='sub-inner-links'>");
document.write("                          <li><a href='paediatrics-general.html'>General Paediatrics</a></li>");
document.write("                          <li><a href='paediatrics-neonatology.html'>Neonatology</a></li>");
document.write("                          <li><a href='paediatric-oncology.html'>Paediatric Hemato-Oncology</a></li>");
document.write("                          <li><a href='paediatric-nephrology.html'>Paediatric Nephrology</a></li>");
document.write("                          <!-- <li><a href='javascript:;'>Paediatric Neurology</a></li> -->");
document.write("                          <li><a href='paediatric-surgery.html'>Paediatric Surgery</a></li>");
document.write("                          <!--<li><a href='javascript:;'>Paediatric Gastrointestinal</a></li>");
document.write("                          <li><a href='javascript:;'>Paediatric Endocrinology</a></li> -->");
document.write("                          <li><a href='paediatric-orthopaedics.html'>Paediatric Orthopaedics</a></li>");
document.write("                        </ul>");
document.write("                      </li> ");
document.write("                    	");
document.write("                      <li>");
document.write("                        <a href='paediatric-cardiac-sciences.html'>Paediatric Cardiac Sciences</a>");
document.write("                      </li>");



document.write("                      <li>");
document.write("                        <a href='javascript:;' class='no-link'>Medical Services</a>");
document.write("                        <ul class='sub-inner-links'>");
document.write("                          <li><a href='internal-medicine.html'>Internal Medicine</a></li>");
document.write("                          <li><a href='infectious-diseases.html'>Infectious Diseases</a></li>");
document.write("                          <li><a href='hematology.html'>Hematology</a></li>");
document.write("                          <li><a href='dermatology.html'>Dermatology</a></li>");
document.write("                          <li><a href='geriatrics.html'>Geriatrics</a></li>");
document.write("                          <li><a href='psychiatry.html'>Psychiatry</a></li>");
document.write("                          <li class='hide'><a href='javascript:;'>Dietetics &amp; Nutrition</a></li> ");
document.write("                        </ul>");
document.write("                      </li> ");


document.write("                    	<li>");
document.write("                        <a href='pulmonary-sleep-medicine.html'>Pulmonary Medicine</a>");
/*document.write("                        <ul class='hide'>");
document.write("                          <li><a href='javascript:;'>Internal Medicine</a></li>");
document.write("                          <li><a href='javascript:;'>Infectious Diseases</a></li>");
document.write("                          <li><a href='javascript:;'>Geriatrics</a></li>");
document.write("                          <li><a href='javascript:;'>Dermatology</a></li>");
document.write("                          <li><a href='javascript:;'>Dietetics &amp; Nutrition</a></li> ");
document.write("                        </ul>");*/
document.write("                      </li>");
document.write("                       ");
document.write("                    </ul>");
document.write("                  </li>");
document.write("                </ul>              ");
document.write("                <ul class='sub-menu-list'>   ");
document.write("                  <li>");
document.write("                    <ul class='sub-inner-page'>");
/*document.write("                      <li class='hide'>");
document.write("                        <a href='javascript:;' class='no-link'>Endocrinology</a>");
document.write("                        <ul class='hide'>");
document.write("                          <li><a href='javascript:;'>Internal Medicine</a></li>");
document.write("                          <li><a href='javascript:;'>Infectious Diseases</a></li>");
document.write("                          <li><a href='javascript:;'>Geriatrics</a></li>");
document.write("                          <li><a href='javascript:;'>Dermatology</a></li>");
document.write("                          <li><a href='javascript:;'>Dietetics &amp; Nutrition</a></li> ");
document.write("                        </ul>")
document.write("                      </li>");;*/
document.write("                      <li>");
document.write("                        <a href='gastroenterology.html'>Gastroenterology</a>");
/*document.write("                        <ul class='hide'>");
document.write("                          <li><a href='javascript:;'>Internal Medicine</a></li>");
document.write("                          <li><a href='javascript:;'>Infectious Diseases</a></li>");
document.write("                          <li><a href='javascript:;'>Geriatrics</a></li>");
document.write("                          <li><a href='javascript:;'>Dermatology</a></li>");
document.write("                          <li><a href='javascript:;'>Dietetics &amp; Nutrition</a></li> ");
document.write("                        </ul>");*/
document.write("                      </li>"); 
document.write("                      <li>");
document.write("                        <a href='endocrinology.html'>Endocrinology</a>");
/*document.write("                        <ul class='hide'>");
document.write("                          <li><a href='javascript:;'>Urology</a></li>");
document.write("                          <li><a href='javascript:;'>Nephrology</a></li>");
document.write("                        </ul>");*/
document.write("                      </li>");
document.write("                    	<li>");
document.write("                        <a href='rheumatology.html'>Rheumatology</a>");
/*document.write("                        <ul class='hide'>");
document.write("                          <li><a href='javascript:;'>Internal Medicine</a></li>");
document.write("                          <li><a href='javascript:;'>Infectious Diseases</a></li>");
document.write("                          <li><a href='javascript:;'>Geriatrics</a></li>");
document.write("                          <li><a href='javascript:;'>Dermatology</a></li>");
document.write("                          <li><a href='javascript:;'>Dietetics &amp; Nutrition</a></li> ");
document.write("                        </ul>");*/
document.write("                      </li>");
document.write("                      <li class='hide'>");
document.write("                        <a href='javascript:;' class='no-link'>Haematology</a>");
/*document.write("                        <ul class='hide'>");
document.write("                          <li><a href='javascript:;'>Internal Medicine</a></li>");
document.write("                          <li><a href='javascript:;'>Infectious Diseases</a></li>");
document.write("                          <li><a href='javascript:;'>Geriatrics</a></li>");
document.write("                          <li><a href='javascript:;'>Dermatology</a></li>");
document.write("                          <li><a href='javascript:;'>Dietetics &amp; Nutrition</a></li> ");
document.write("                        </ul>");*/
document.write("                      </li>"); 
document.write("                      <li>");
document.write("                        <a href='javascript:;' class='no-link'>Surgical Services</a>");
document.write("                        <ul class='sub-inner-links'>");
document.write("                          <li><a href='general-minimal-surgery.html'>General and Minimal Access Surgery</a></li>");
document.write("                          <li><a href='thoracic-surgery.html'>Thoracic Surgery</a></li>");
document.write("                          <li><a href='vascular-surgery.html'>Vascular Surgery</a></li>");
document.write("                          <li><a href='hepato-biliary-pancreatic-surgery.html'>Hepato-Pancreatico-Biliary (HPB) Surgery</a></li> ");
document.write("                          <li><a href='gastrointestinal-colorectal-surgery.html'>Gastrointestinal &amp; Colorectal Surgery</a></li> ");
document.write("                          <li><a href='bariatric-surgery.html'>Bariatric Surgery</a></li>");
document.write("                          <li><a href='plastic-reconstructive-surgery.html'>Plastic &amp; Reconstructive Surgery</a></li>");
document.write("                        </ul>");
document.write("                      </li>"); 
document.write("                      <li>");
document.write("                        <a href='ophthalmology.html'>Ophthalmology</a>");
//document.write("                        <ul class='hide'>");
//document.write("                          <li><a href='javascript:;'>General &amp; Minimal Access Surgery</a></li>");
//document.write("                          <li><a href='javascript:;'>GI &amp; Hepatobiliary Surgery</a></li>");
//document.write("                          <li><a href='javascript:;'>Thoracic Surgery</a></li>");
//document.write("                          <li><a href='javascript:;'>Vascular Surgery</a></li> ");
//document.write("                        </ul>");
document.write("                      </li>"); 
document.write("                      <li>");
document.write("                        <a href='ear-nose-throat.html'>Ear Nose Throat</a>");
/*document.write("                        <ul class='hide'>");
document.write("                          <li><a href='javascript:;'>General &amp; Minimal Access Surgery</a></li>");
document.write("                          <li><a href='javascript:;'>GI &amp; Hepatobiliary Surgery</a></li>");
document.write("                          <li><a href='javascript:;'>Thoracic Surgery</a></li>");
document.write("                          <li><a href='javascript:;'>Vascular Surgery</a></li> ");
document.write("                        </ul>");*/
document.write("                      </li>");
document.write("                      <li>");
document.write("                        <a href='dental-services.html'>Dental Services</a>");
/*document.write("                        <ul class='hide'>");
document.write("                          <li><a href='javascript:;'>General &amp; Minimal Access Surgery</a></li>");
document.write("                          <li><a href='javascript:;'>GI &amp; Hepatobiliary Surgery</a></li>");
document.write("                          <li><a href='javascript:;'>Thoracic Surgery</a></li>");
document.write("                          <li><a href='javascript:;'>Vascular Surgery</a></li> ");
document.write("                        </ul>");*/
document.write("                      </li>                        ");
document.write("                      ");
document.write("                    </ul>");
document.write("                  </li> ");
document.write("                </ul>         ");
document.write("                <ul class='sub-menu-list'>   ");
document.write("                  <li>");
document.write("                    <ul class='sub-inner-page'>  ");
document.write("                      <li>");
document.write("                        <a href='intensive-care-unit.html'>Critical Care Medicine</a>");
document.write("                      </li>  ");
document.write("                      <li>");
document.write("                        <a href='emergency-medical-services.html'>Emergency Medical Services</a>");
/*document.write("                        <ul class='hide'>");
document.write("                          <li><a href='javascript:;'>Urology</a></li>");
document.write("                          <li><a href='javascript:;'>Nephrology</a></li>");
document.write("                        </ul>");*/
document.write("                      </li>  ");
document.write("                      <li>");
document.write("                        <a href='javascript:;' class='no-link'>Rehabilitation and Sports Medicine</a>");
document.write("                        <ul class='sub-inner-links'>");
document.write("                          <li><a href='center-rehab-medicine.html'>Centre for Rehabilitation Medicine</a></li>");
document.write("                          <li><a href='centre-for-sports-medicine.html'>Centre for Sports Medicine</a></li>");
document.write("                          <li><a href='yoga-studio.html'>Yoga - Holistic Healing</a></li>");
document.write("                        </ul>");
document.write("                      </li> ");
document.write("                      <li>");
document.write("                        <a href='anaesthesia-and-pain-management.html'>Anaesthesia and Pain Management</a>");
document.write("                      </li> ");
document.write("                      <li>");
document.write("                        <a href='nutrition-dietetics.html'>Nutrition &amp; Dietetics</a>");
document.write("                      </li>  ");
document.write("                      <li>");
document.write("                        <a href='executive-health-checkup.html'>Executive Health Check up</a>");
document.write("                        <ul class='sub-inner-links hide'>");
document.write("                          <li><a href='executive-health-checkup-pkg1.html'>Comprehensive Health Package</a></li>");
document.write("                          <li><a href='executive-health-checkup-pkg2.html'>Cardiac Health Package</a></li>");
document.write("                          <li><a href='executive-health-checkup-pkg3.html'>Cardiac Health Plus Package</a></li>");
document.write("                          <li><a href='executive-health-checkup-pkg4.html'>Executive Health Package</a></li>");
document.write("                          <li><a href='executive-health-checkup-pkg5.html'>Executive Health Plus Package</a></li>");
document.write("                          <li><a href='executive-health-checkup-pkg6.html'>Men's Health Package</a></li>  ");
document.write("                          <li><a href='executive-health-checkup-pkg7.html'>Well Woman Package</a></li>  ");
document.write("                          <li><a href='executive-health-checkup-pkg8.html'>Stay Fit Package</a></li>  ");
document.write("                          <li><a href='executive-health-checkup-pkg9.html'>Pre-marital Health Package</a></li>  ");
document.write("                          <li><a href='executive-health-checkup-pkg10.html'>Child Health Package</a></li>");
document.write("                          <li><a href='executive-health-checkup-pkg11.html'>Primary Health Package</a></li>");
document.write("                        </ul>");
document.write("                      </li>");
document.write("                      <li>");
document.write("                        <a class='no-link'>Diagnostic Services</a> ");
document.write("                        <ul class='sub-inner-links'>");
document.write("                          <li><a href='radiology.html'>Radiology &amp; Imaging</a></li>");
document.write("                          <li><a href='nuclear-medicine.html'>Nuclear Medicine</a></li> ");
document.write("                          <li><a href='laboratory-medicine.html'>Laboratory Medicine</a>");
document.write("                        <ul class='sub-inner-links'>");
document.write("                          <li><a href='home-collection.html'>Home Collection</a></li>");
document.write("                        </ul>");
document.write("                      </li>");
document.write("                        </ul>");
document.write("                      </li>  ");
document.write("                      <li>");
document.write("                        <a href='blood-bank.html'>Blood Bank</a> ");
document.write("                        <ul class='sub-inner-links hide'>");
document.write("                          <li><a href='radiology.html'>Radiology &amp; Imaging</a></li>");
document.write("                          <li><a href='laboratory-medicine.html'>Laboratory Medicine</a></li>");
document.write("                          <li><a href='nuclear-medicine.html'>Nuclear Medicine</a></li> ");
document.write("                        </ul>");
document.write("                      </li>  ");
document.write("                    </ul>");
document.write("                  </li> ");
document.write("                </ul>                 ");
document.write("              </li>");
document.write("            </ul>");
document.write("          </li>");
document.write("          <li>");
document.write("            <a href='patients-visitor-services.html'>Patients &amp; Visitor Services</a>");
document.write("            <ul class='sub-menu patient-position clearfix hide'>");
document.write("              <li class='clearfix'>            	");
document.write("                <ul class='sub-menu-list'>");
document.write("                  <li>");
document.write("                    <h3><a class='no-link'>Outpatient Visit</a></h3>");
document.write("                    <ul class='sub-inner-page'>");
document.write("                      <li>");
document.write("                        <a href='appointment-scheduling.html'>Appointment Scheduling</a>");
document.write("                      </li>");
document.write("                      <li>");
document.write("                        <a href='registration.html'>Registration</a>");
document.write("                      </li>");
document.write("                      <li>");
document.write("                        <a href='billing-payments.html'>Billing and Payments</a>");
document.write("                      </li>");
document.write("                      <li>");
document.write("                        <a href='opd-preparing-for-opd.html'>OPD Services</a>");
document.write("                      </li>");
document.write("                      <li>");
document.write("                        <a href='opd-preparing-for-opd.html#opdsection'>Preparing for OPD</a>");
document.write("                      </li>");
document.write("                    </ul>");
document.write("                    <h3><a class='no-link'>Inpatient Stay</a></h3>");
document.write("                    <ul class='sub-inner-page'>");
document.write("                      <li>");
document.write("                        <a href='admission.html'>Admission Guidelines</a>");
document.write("                      </li>");
document.write("                      <li>");
document.write("                        <a href='billings-payments.html'>Billing</a>");
document.write("                      </li>");
/*document.write("                      <li>");
document.write("                        <a href='tpa-corporate-partners.html'>TPA &amp; Corporate Partners</a>");
document.write("                      </li>");*/
document.write("                      <li>");
document.write("                        <a href='visitors-information.html'>Visitor's Information</a>");
document.write("                      </li> ");
document.write("                    </ul> ");
document.write("                    <h3><a href='day-care.html'>Day Care Services</a></h3>");
document.write("                  </li>");
document.write("                </ul>              ");
document.write("                <ul class='sub-menu-list'>");
document.write("                  <li>");
document.write("                    <h3><a href='facilities.html'>Facilities</a></h3>");
document.write("                    <ul class='sub-inner-page'>");
document.write("                      <li>");
document.write("                        <a href='room-types.html'>Room Types</a>");
document.write("                      </li>");
/*document.write("                      <li>");
document.write("                        <a href='child-care.html'>Child Care</a>");
document.write("                      </li>");*/
document.write("                      <li>");
document.write("                        <a href='other-amenities.html'>");
document.write("                          Other Amenities");
document.write("                        </a>");
document.write("                      </li>"); 
document.write("                    </ul>");
document.write("                    <h3><a class='no-link'>Tariff</a></h3>");
document.write("                    <ul class='sub-inner-page'>");
document.write("                      <li>");
document.write("                        <a href='tariff.html'>Room Tariff</a>");
document.write("                      </li>");
/*document.write("                      <li>");
document.write("                        <a href='child-care.html'>Child Care</a>");
document.write("                      </li>");*/
document.write("                      <li>");
document.write("                        <a href='diagnostic-charges.html'>");
document.write("                          Diagnostic Charges");
document.write("                        </a>");
document.write("                      </li>"); 
document.write("                      <li>");
document.write("                        <a href='https://epayments.rfhospital.org/'>");
document.write("                          Online Payment");
document.write("                        </a>");
document.write("                      </li>"); 
document.write("                    </ul>");
document.write("                    <h3><a href='patient-charter.html'>Patientsâ€™ Rights &amp; Responsibilities </a></h3>");
document.write("                    <h3><a href='empanelled-insurance-companies.html'>Empanelled Insurance Companies &amp; TPAs</a></h3>");
document.write("                    <h3><a href='frmfeedback.aspx'>Feedback</a></h3>");
/*document.write("                    <h3 class='pt25em'><a href='tariff-schedule.html' class='pb25em'>Tariff Schedule</a></h3>");
document.write("                    <h3 class='pt25em hide'><a href='http://10.128.22.72:85/frmLogin.aspx'>My RFH Login</a></h3>");*/ 
document.write("                  </li>");
document.write("                </ul>");
document.write("                <ul class='sub-menu-list last'>");
document.write("                  <li>");
document.write("                    <img src='img/submenu_img1.jpg' alt='Submenu Image'>");
document.write("                    <h3 class='hide'>Lorem Ipsum Proin gravida </h3>");
document.write("                    <p class='hide'>Nisbh vel velit auctor aliquet. Aenean sollicitudin, lorem quis bibendum auctornisi elit consequat</p>");
document.write("                  </li>");
document.write("                </ul>                 ");
document.write("              </li>");
document.write("            </ul>");
document.write("          </li>");
document.write("          <li class='healthProf'>");
document.write("            <a href='health-care-professional.html'>Healthcare Professionals</a>");

/*Start
document.write("            <ul class='sub-menu health-position clearfix hide'>");
document.write("              <li class='clearfix'>            	");
document.write("                <ul class='sub-menu-list clearfix'>");
document.write("                  <li>");
document.write("                    <h3><a href='#'>Department of Nursing</a></h3>");
document.write("                  </li>");
document.write("                  <li>");
document.write("                    <h3><a href='#'>Doctor's Directory</a></h3>");
document.write("                  </li>");
document.write("                  <li>");
document.write("                    <h3><a href='#'>Careers</a></h3>");
document.write("                  </li>");
document.write("                </ul>");
document.write("              </li>");
document.write("            </ul>");*/
/*End*/

document.write(" <ul class='sub-menu health-position clearfix hide'");
document.write(" <li class='clearfix'>");
/*document.write(" <ul class='sub-menu-list clearfix'>");
document.write(" <li>");
document.write("         <h3><a href='respect-life.html'>Respect For Life</a></h3>");
document.write(" </li>");
document.write(" <li>");
document.write("         <h3><a href='chairperson-message.html'>Chairperson's Message</a></h3>");
document.write(" </li>");
document.write(" <li>");
document.write("         <h3><a href='our-pledge.html'>Our Pledge</a></h3>");
document.write(" </li>");
document.write(" </ul>");*/
document.write(" <ul class='sub-menu-list'>");
document.write(" <li>");
document.write("         <h3><a href='dept-of-nursing.html'>Department of Nursing</a></h3>");
document.write(" </li>");
document.write(" <li>");
document.write("         <h3><a href='doctor-directory.html'>Doctors' Directory</a></h3>");
document.write(" </li>");
document.write(" <li>");
document.write("         <h3><a href='careers.html'>Careers</a></h3>");
document.write(" </li>");
document.write(" </ul>");
document.write(" <ul class='sub-menu-list last'>");
document.write(" <li>");
document.write("         <img src='images/submenu_healthcare.jpg' alt='Submenu Image'>");
document.write("         <h3 class='hide'>Lorem Ipsum Proin gravida </h3>");
document.write("         <p class='hide'>Nisbh vel velit auctor aliquet. Aenean sollicitudin.</p>");
document.write(" </li>");
document.write(" </ul>");
document.write(" </li>");
document.write(" </ul>");



document.write("          </li>");
/*document.write("          <li>");
document.write("            <a href='careers.html'>Careers</a>");
document.write("          </li>");*/
document.write("        </ul>");
document.write("      </div>");
document.write("      <!-- End Header Menu -->");
document.write("      <!-- Login section -->");
document.write("      <div class='login-section'> ");
document.write("        <ul class='unstyled-list login-link clearfix'>");
document.write("          <li><a href='https://myaccount.rfhospital.org/'>LOGIN</a></li>");
/*document.write("          <li class='hidden'><a href='frmBookAnAppointment.aspx'>REGISTER</a></li>");*/
/*document.write("          <li class='no-bl select_box'><a class='select_lang'> <select id='lang_select'>");
document.write("           <option value='eng' selected>ENGLISH</option>");
document.write("           <option value='hin' >à¤¹à¤¿à¤¨à¥à¤¦à¥€</option>");
document.write("          </select></</li>");*/
document.write("          <li><a href='contact-us.html'>CONTACT US</a></li>");
document.write("          <li class='no-border-left'><a class='mayIHelp' href='javascript:;'>May I help you</a></li> ");
document.write("        </ul>");
document.write("        <span class='call-on'>1-800-221-166</span>");
document.write("      </div>  ");
document.write("      <!-- End Login section -->");
document.write("    </header>      ");
document.write("    <!-- End Header -->     ");
document.write("  </div>");
/*document.write(" <script type='text/javascript' src='html5lightbox.js'></script>");*/
function toggleSidebar(){
		
		if($('.side-slider').css('right') === "-363px"){
			$('.side-slider').stop().animate({ "right" : "-18px" }, 800, "easeOutCubic");
			$('.for').stop().animate({ "padding" : "1.5em"}, 1500, "easeOutCubic"); 
		}	
		
		$('.sliding-doc-info').stop().animate({ "top" : "-230" }, 800, "easeOutCubic");
		
};

/**/
<!-- Piwik -->
  var _paq = _paq || [];
  _paq.push(["trackPageView"]);
  _paq.push(["enableLinkTracking"]);

  (function() {
    var u=(("https:" == document.location.protocol) ? "https" : "http") + "://webanalytics.ril.com/analytics/piwik/";
    _paq.push(["setTrackerUrl", u+"piwik.php"]);
    _paq.push(["setSiteId", "21"]);
    var d=document, g=d.createElement("script"), s=d.getElementsByTagName("script")[0]; g.type="text/javascript";
    g.defer=true; g.async=true; g.src=u+"piwik.js"; s.parentNode.insertBefore(g,s);
  })();
<!-- End Piwik Code -->
<!--google analytics code-->
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-63861062-1', 'auto');
  ga('send', 'pageview');
<!--google analytics code ends-->